module.exports = {
    OCEAN_PENDING: "OCEAN_PENDING",

    PROSPEO_PENDING: "PROSPEO_PENDING",

    REVIEW_PENDING: "REVIEW_PENDING",

    BREVO_PENDING: "BREVO_PENDING",

    COMPLETED: "COMPLETED",

    FAILED: "FAILED"
};